import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ReportData {
    title: string;
    subtitle?: string;
    businessName?: string;
    dateRange?: string;
    sections: ReportSection[];
}

export interface ReportSection {
    title: string;
    type: 'table' | 'text' | 'chart';
    data: any;
}

export class PDFExportService {
    /**
     * Generate and download a business report as PDF
     */
    static async generateReport(reportData: ReportData): Promise<void> {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        let yPos = 20;

        // Header - Company Name & Logo placeholder
        doc.setFontSize(24);
        doc.setTextColor(67, 56, 202); // Indigo
        doc.text(reportData.title, pageWidth / 2, yPos, { align: 'center' });

        yPos += 10;

        // Subtitle (business name)
        if (reportData.businessName) {
            doc.setFontSize(12);
            doc.setTextColor(100, 116, 139); // Gray
            doc.text(reportData.businessName, pageWidth / 2, yPos, { align: 'center' });
            yPos += 8;
        }

        // Date range
        if (reportData.dateRange) {
            doc.setFontSize(10);
            doc.text(reportData.dateRange, pageWidth / 2, yPos, { align: 'center' });
            yPos += 15;
        }

        // Line separator
        doc.setDrawColor(226, 232, 240);
        doc.setLineWidth(0.5);
        doc.line(20, yPos, pageWidth - 20, yPos);
        yPos += 10;

        // Render each section
        for (const section of reportData.sections) {
            // Check if need new page
            if (yPos > 250) {
                doc.addPage();
                yPos = 20;
            }

            // Section title
            doc.setFontSize(14);
            doc.setTextColor(0, 0, 0);
            doc.text(section.title, 20, yPos);
            yPos += 8;

            if (section.type === 'table' && section.data.headers && section.data.rows) {
                // Render table using autoTable
                (doc as any).autoTable({
                    startY: yPos,
                    head: [section.data.headers],
                    body: section.data.rows,
                    theme: 'striped',
                    headStyles: {
                        fillColor: [67, 56, 202], // Indigo
                        textColor: [255, 255, 255],
                        fontSize: 10,
                        fontStyle: 'bold'
                    },
                    bodyStyles: {
                        fontSize: 9
                    },
                    alternateRowStyles: {
                        fillColor: [248, 250, 252]
                    },
                    margin: { left: 20, right: 20 }
                });

                yPos = (doc as any).lastAutoTable.finalY + 15;

            } else if (section.type === 'text') {
                // Render text content
                doc.setFontSize(10);
                doc.setTextColor(51, 65, 85);

                const lines = doc.splitTextToSize(section.data, pageWidth - 40);
                lines.forEach((line: string) => {
                    if (yPos > 280) {
                        doc.addPage();
                        yPos = 20;
                    }
                    doc.text(line, 20, yPos);
                    yPos += 6;
                });
                yPos += 10;

            } else if (section.type === 'chart') {
                // For charts, render as data table
                doc.setFontSize(9);
                doc.setTextColor(100);
                doc.text('(Chart data displayed as table)', 20, yPos);
                yPos += 10;
            }
        }

        // Footer
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(150);
            doc.text(
                `Generated by NexVyapaar - Page ${i} of ${pageCount}`,
                pageWidth / 2,
                doc.internal.pageSize.getHeight() - 10,
                { align: 'center' }
            );
            doc.text(
                new Date().toLocaleString(),
                pageWidth - 20,
                doc.internal.pageSize.getHeight() - 10,
                { align: 'right' }
            );
        }

        // Download the PDF
        const fileName = `${reportData.title.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`;
        doc.save(fileName);
    }

    /**
     * Generate inventory report
     */
    static async generateInventoryReport(materials: any[], businessName: string): Promise<void> {
        const reportData: ReportData = {
            title: 'Inventory Report',
            businessName,
            dateRange: `Generated on ${new Date().toLocaleDateString()}`,
            sections: [
                {
                    title: 'Inventory Summary',
                    type: 'text',
                    data: `Total Items: ${materials.length}\nTotal Value: ₹${materials.reduce((sum, m) => sum + (m.current_stock * m.cost_per_unit), 0).toLocaleString()}`
                },
                {
                    title: 'Inventory Details',
                    type: 'table',
                    data: {
                        headers: ['Item Name', 'Stock', 'Unit', 'Cost', 'Selling Price', 'Value'],
                        rows: materials.map(m => [
                            m.name,
                            m.current_stock.toString(),
                            m.unit,
                            `₹${m.cost_per_unit}`,
                            `₹${m.selling_price || m.cost_per_unit}`,
                            `₹${(m.current_stock * m.cost_per_unit).toLocaleString()}`
                        ])
                    }
                }
            ]
        };

        await this.generateReport(reportData);
    }

    /**
     * Generate sales report
     */
    static async generateSalesReport(sales: any[], businessName: string, dateRange: string): Promise<void> {
        const totalRevenue = sales.reduce((sum, s) => sum + ((s.price || 0) * (s.quantity || 0)), 0);

        const reportData: ReportData = {
            title: 'Sales Report',
            businessName,
            dateRange,
            sections: [
                {
                    title: 'Sales Summary',
                    type: 'text',
                    data: `Total Sales: ${sales.length}\nTotal Revenue: ₹${totalRevenue.toLocaleString()}\nAverage Sale Value: ₹${(totalRevenue / (sales.length || 1)).toFixed(2)}`
                },
                {
                    title: 'Sales Details',
                    type: 'table',
                    data: {
                        headers: ['Date', 'Product', 'Quantity', 'Price', 'Total'],
                        rows: sales.map(s => [
                            new Date(s.sale_date).toLocaleDateString(),
                            s.product_name,
                            s.quantity.toString(),
                            `₹${s.price || 0}`,
                            `₹${((s.price || 0) * (s.quantity || 0)).toLocaleString()}`
                        ])
                    }
                }
            ]
        };

        await this.generateReport(reportData);
    }

    /**
     * Generate comprehensive business report
     */
    static async generateBusinessReport(
        materials: any[],
        sales: any[],
        suppliers: any[],
        businessName: string
    ): Promise<void> {
        const totalInventoryValue = materials.reduce((sum, m) => sum + (m.current_stock * m.cost_per_unit), 0);
        const totalRevenue = sales.reduce((sum, s) => sum + ((s.price || 0) * (s.quantity || 0)), 0);

        const reportData: ReportData = {
            title: 'Business Overview Report',
            businessName,
            dateRange: `As of ${new Date().toLocaleDateString()}`,
            sections: [
                {
                    title: 'Executive Summary',
                    type: 'text',
                    data: `Total Inventory Items: ${materials.length}\nTotal Inventory Value: ₹${totalInventoryValue.toLocaleString()}\n\nTotal Sales: ${sales.length}\nTotal Revenue: ₹${totalRevenue.toLocaleString()}\n\nActive Suppliers: ${suppliers.length}`
                },
                {
                    title: 'Top Inventory Items',
                    type: 'table',
                    data: {
                        headers: ['Item', 'Stock', 'Value'],
                        rows: materials
                            .sort((a, b) => (b.current_stock * b.cost_per_unit) - (a.current_stock * a.cost_per_unit))
                            .slice(0, 10)
                            .map(m => [
                                m.name,
                                `${m.current_stock} ${m.unit}`,
                                `₹${(m.current_stock * m.cost_per_unit).toLocaleString()}`
                            ])
                    }
                },
                {
                    title: 'Suppliers',
                    type: 'table',
                    data: {
                        headers: ['Supplier Name', 'Contact', 'Products'],
                        rows: suppliers.map(s => [
                            s.name,
                            s.phone || 'N/A',
                            (s.products_supplied || []).join(', ')
                        ])
                    }
                }
            ]
        };

        await this.generateReport(reportData);
    }
}
